apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-logs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-airflow-logs
  nfs:
    server: 172.31.3.234
    path: /mnt/data/airflow/logs