name: CI

on:
  push:
    branches:
      - feature/argocd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: team02k8s
        password: rlaehdgus

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: spark
        push: true
        tags: user/app:latest

